/* tslint:disable */
/* eslint-disable */
/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { EmploymentContractPendingChangesResponse } from '../models';
// @ts-ignore
import { NotFoundResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmploymentContractsApi - axios parameter creator
 * @export
 */
export const EmploymentContractsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all the pending changes (waiting for aproval or signature) for the employment contract.
         * @summary Get employment contract pending changes
         * @param {string} employmentId Employment ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPendingChanges: async (employmentId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employmentId' is not null or undefined
            assertParamExists('getPendingChanges', 'employmentId', employmentId)
            const localVarPath = `/v1/employment-contracts/{employment_id}/pending-changes`
                .replace(`{${"employment_id"}}`, encodeURIComponent(String(employmentId !== undefined ? employmentId : `-employment_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)
            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employment-contracts/{employment_id}/pending-changes',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmploymentContractsApi - functional programming interface
 * @export
 */
export const EmploymentContractsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmploymentContractsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all the pending changes (waiting for aproval or signature) for the employment contract.
         * @summary Get employment contract pending changes
         * @param {EmploymentContractsApiGetPendingChangesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPendingChanges(requestParameters: EmploymentContractsApiGetPendingChangesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmploymentContractPendingChangesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPendingChanges(requestParameters.employmentId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmploymentContractsApi - factory interface
 * @export
 */
export const EmploymentContractsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmploymentContractsApiFp(configuration)
    return {
        /**
         * Get all the pending changes (waiting for aproval or signature) for the employment contract.
         * @summary Get employment contract pending changes
         * @param {EmploymentContractsApiGetPendingChangesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPendingChanges(requestParameters: EmploymentContractsApiGetPendingChangesRequest, options?: AxiosRequestConfig): AxiosPromise<EmploymentContractPendingChangesResponse> {
            return localVarFp.getPendingChanges(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getPendingChanges operation in EmploymentContractsApi.
 * @export
 * @interface EmploymentContractsApiGetPendingChangesRequest
 */
export type EmploymentContractsApiGetPendingChangesRequest = {
    
    /**
    * Employment ID
    * @type {string}
    * @memberof EmploymentContractsApiGetPendingChanges
    */
    readonly employmentId: string
    
}

/**
 * EmploymentContractsApiGenerated - object-oriented interface
 * @export
 * @class EmploymentContractsApiGenerated
 * @extends {BaseAPI}
 */
export class EmploymentContractsApiGenerated extends BaseAPI {
    /**
     * Get all the pending changes (waiting for aproval or signature) for the employment contract.
     * @summary Get employment contract pending changes
     * @param {EmploymentContractsApiGetPendingChangesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmploymentContractsApiGenerated
     */
    public getPendingChanges(requestParameters: EmploymentContractsApiGetPendingChangesRequest, options?: AxiosRequestConfig) {
        return EmploymentContractsApiFp(this.configuration).getPendingChanges(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
