/* tslint:disable */
/* eslint-disable */
/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BadRequestResponse } from '../models';
// @ts-ignore
import { NotFoundResponse } from '../models';
// @ts-ignore
import { OAuth2TokenParams } from '../models';
// @ts-ignore
import { OAuth2Tokens } from '../models';
// @ts-ignore
import { TooManyRequestsResponse } from '../models';
// @ts-ignore
import { UnauthorizedResponse } from '../models';
// @ts-ignore
import { UnprocessableEntityResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * OAuth2Api - axios parameter creator
 * @export
 */
export const OAuth2ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Endpoint to exchange tokens in the Authorization Code, Client Credentials and Refresh Token flows
         * @summary Token
         * @param {OAuth2TokenParams} [oAuth2TokenParams] OAuth2Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exchangeToken: async (oAuth2TokenParams?: OAuth2TokenParams, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/oauth2/token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)
            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: oAuth2TokenParams,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/auth/oauth2/token',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(oAuth2TokenParams, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OAuth2Api - functional programming interface
 * @export
 */
export const OAuth2ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OAuth2ApiAxiosParamCreator(configuration)
    return {
        /**
         * Endpoint to exchange tokens in the Authorization Code, Client Credentials and Refresh Token flows
         * @summary Token
         * @param {OAuth2ApiExchangeTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exchangeToken(requestParameters: OAuth2ApiExchangeTokenRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OAuth2Tokens>> {
            const oAuth2TokenParams: OAuth2TokenParams = {
                code: requestParameters.code,
                grant_type: requestParameters.grant_type
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.exchangeToken(oAuth2TokenParams, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OAuth2Api - factory interface
 * @export
 */
export const OAuth2ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OAuth2ApiFp(configuration)
    return {
        /**
         * Endpoint to exchange tokens in the Authorization Code, Client Credentials and Refresh Token flows
         * @summary Token
         * @param {OAuth2ApiExchangeTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exchangeToken(requestParameters: OAuth2ApiExchangeTokenRequest = {}, options?: AxiosRequestConfig): AxiosPromise<OAuth2Tokens> {
            return localVarFp.exchangeToken(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for exchangeToken operation in OAuth2Api.
 * @export
 * @interface OAuth2ApiExchangeTokenRequest
 */
export type OAuth2ApiExchangeTokenRequest = {
    
} & OAuth2TokenParams

/**
 * OAuth2ApiGenerated - object-oriented interface
 * @export
 * @class OAuth2ApiGenerated
 * @extends {BaseAPI}
 */
export class OAuth2ApiGenerated extends BaseAPI {
    /**
     * Endpoint to exchange tokens in the Authorization Code, Client Credentials and Refresh Token flows
     * @summary Token
     * @param {OAuth2ApiExchangeTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OAuth2ApiGenerated
     */
    public exchangeToken(requestParameters: OAuth2ApiExchangeTokenRequest = {}, options?: AxiosRequestConfig) {
        return OAuth2ApiFp(this.configuration).exchangeToken(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
