/* tslint:disable */
/* eslint-disable */
/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BadRequestResponse } from '../models';
// @ts-ignore
import { ForbiddenResponse } from '../models';
// @ts-ignore
import { InternalServerErrorResponse } from '../models';
// @ts-ignore
import { NotFoundResponse } from '../models';
// @ts-ignore
import { TooManyRequestsResponse } from '../models';
// @ts-ignore
import { UnauthorizedResponse } from '../models';
// @ts-ignore
import { UnprocessableEntityResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ResignationApi - axios parameter creator
 * @export
 */
export const ResignationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Downloads a resignation letter from an employment request.
         * @summary Download a resignation letter
         * @param {string} employmentRequestId The employment request ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadLetter: async (employmentRequestId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employmentRequestId' is not null or undefined
            assertParamExists('downloadLetter', 'employmentRequestId', employmentRequestId)
            const localVarPath = `/v1/resignations/{employment_request_id}/resignation-letter`
                .replace(`{${"employment_request_id"}}`, encodeURIComponent(String(employmentRequestId !== undefined ? employmentRequestId : `-employment_request_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)
            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/resignations/{employment_request_id}/resignation-letter',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResignationApi - functional programming interface
 * @export
 */
export const ResignationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ResignationApiAxiosParamCreator(configuration)
    return {
        /**
         * Downloads a resignation letter from an employment request.
         * @summary Download a resignation letter
         * @param {ResignationApiDownloadLetterRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadLetter(requestParameters: ResignationApiDownloadLetterRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Uint8Array | File | buffer.File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadLetter(requestParameters.employmentRequestId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ResignationApi - factory interface
 * @export
 */
export const ResignationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ResignationApiFp(configuration)
    return {
        /**
         * Downloads a resignation letter from an employment request.
         * @summary Download a resignation letter
         * @param {ResignationApiDownloadLetterRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadLetter(requestParameters: ResignationApiDownloadLetterRequest, options?: AxiosRequestConfig): AxiosPromise<Uint8Array | File | buffer.File> {
            return localVarFp.downloadLetter(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for downloadLetter operation in ResignationApi.
 * @export
 * @interface ResignationApiDownloadLetterRequest
 */
export type ResignationApiDownloadLetterRequest = {
    
    /**
    * The employment request ID
    * @type {string}
    * @memberof ResignationApiDownloadLetter
    */
    readonly employmentRequestId: string
    
}

/**
 * ResignationApiGenerated - object-oriented interface
 * @export
 * @class ResignationApiGenerated
 * @extends {BaseAPI}
 */
export class ResignationApiGenerated extends BaseAPI {
    /**
     * Downloads a resignation letter from an employment request.
     * @summary Download a resignation letter
     * @param {ResignationApiDownloadLetterRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResignationApiGenerated
     */
    public downloadLetter(requestParameters: ResignationApiDownloadLetterRequest, options?: AxiosRequestConfig) {
        return ResignationApiFp(this.configuration).downloadLetter(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
