/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AmountTaxType } from './amount-tax-type';

/**
 * 
 * @export
 * @interface CommonIncentiveParams
 */
export interface CommonIncentiveParams {
    /**
     * The amount (in the currency of the employment) to be given to the employee.  This field accepts fractional amounts as well. However to avoid precision issues and errors that can arise from storing fractional amounts, the Remote API only accepts currencies and their fractional amounts as integers. This means you should append fractional amounts to the end of the amount you\'re passing in with this field.  For example, if the incentive you\'re offering is EUR 500.25, you would specify `50025` as the amount for this field. 
     * @type {number}
     * @memberof CommonIncentiveParams
     */
    'amount'?: number;
    /**
     *   Whether the amount given accounts for taxes or not.    `gross` indicates that the amount given is the amount to be paid before taxes   are subtracted.    `net` indicates that the amount given is the amount which will be paid to the   employee after taxes. Remote will gross this up to ensure the taxes are   included and employee receives the amount requested without further reduction. 
     * @type {AmountTaxType}
     * @memberof CommonIncentiveParams
     */
    'amount_tax_type'?: AmountTaxType;
    /**
     * The date at which the incentive should take effect.  Note that the incentive is not paid out on the effective date, but during the next payroll cycle. The effective date determines which payroll cycle the incentive will be paid out in.  The effective date needs to be today or a future date.  Note for recurring incentives: since the months don\'t have the same amount of days, if day of month of `effective_date` is one of [28, 29, 30, 31] it will be transformed to the last day of each month, avoiding the possibility of skipping a month in the recurrence. 
     * @type {string}
     * @memberof CommonIncentiveParams
     */
    'effective_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonIncentiveParams
     */
    'note'?: string | null;
}

