/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RequestDetails } from './request-details';

/**
 * Contract Amendment
 * @export
 * @interface ContractAmendment
 */
export interface ContractAmendment {
    /**
     * 
     * @type {string}
     * @memberof ContractAmendment
     */
    'amendment_contract_id': string | null;
    /**
     * Describes all the changes requested for the contract and contract details with all their previous and current values.
     * @type {object}
     * @memberof ContractAmendment
     */
    'changes': object;
    /**
     * 
     * @type {string}
     * @memberof ContractAmendment
     */
    'employment_id': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAmendment
     */
    'id': string;
    /**
     * 
     * @type {RequestDetails}
     * @memberof ContractAmendment
     */
    'request_details': RequestDetails;
    /**
     * 
     * @type {string}
     * @memberof ContractAmendment
     */
    'requested_by': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAmendment
     */
    'status': ContractAmendmentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ContractAmendment
     */
    'submitted_at': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAmendment
     */
    'zendesk_ticket_url': string | null;
}

type ContractAmendmentStatusEnum = 'submitted' | 'in_review' | 'done' | 'canceled' | 'deleted'


