/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CostCalculatorCost } from './cost-calculator-cost';
import { Currency } from './currency';

/**
 * 
 * @export
 * @interface CostCalculatorCosts
 */
export interface CostCalculatorCosts {
    /**
     * The list of all annual benefit costs
     * @type {Array<CostCalculatorCost>}
     * @memberof CostCalculatorCosts
     */
    'annual_benefits_breakdown'?: Array<CostCalculatorCost>;
    /**
     * The annual benefits total that a company must pay for this employment
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'annual_benefits_total'?: number;
    /**
     * The list of all annual employer contribution costs
     * @type {Array<CostCalculatorCost>}
     * @memberof CostCalculatorCosts
     */
    'annual_contributions_breakdown'?: Array<CostCalculatorCost>;
    /**
     * The annual contributions that a company must pay for this employment
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'annual_contributions_total': number;
    /**
     * The annual gross salary that the employee is going to earn
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'annual_gross_salary': number;
    /**
     * The annual gross salary + annual contributions + annual fee (monthly fee * 12) + extra statutory payments if applicable
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'annual_total': number;
    /**
     * 
     * @type {Currency}
     * @memberof CostCalculatorCosts
     */
    'currency': Currency;
    /**
     * The list of all annual extra statutory payment costs
     * @type {Array<CostCalculatorCost>}
     * @memberof CostCalculatorCosts
     */
    'extra_statutory_payments_breakdown'?: Array<CostCalculatorCost>;
    /**
     * 13th month salary, this happens for countries such as Philippines
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'extra_statutory_payments_total': number;
    /**
     * The list of all monthly benefit costs
     * @type {Array<CostCalculatorCost>}
     * @memberof CostCalculatorCosts
     */
    'monthly_benefits_breakdown'?: Array<CostCalculatorCost>;
    /**
     * The benefits total that the company pays monthly
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'monthly_benefits_total'?: number;
    /**
     * The list of all monthly employer contribution costs
     * @type {Array<CostCalculatorCost>}
     * @memberof CostCalculatorCosts
     */
    'monthly_contributions_breakdown'?: Array<CostCalculatorCost>;
    /**
     * The contributions that the company pays monthly
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'monthly_contributions_total': number;
    /**
     * The gross monthly salary for the Employee
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'monthly_gross_salary': number;
    /**
     * Monthly gross salary + monthly contributions  (doesn\'t include fee)
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'monthly_tce': number;
    /**
     * Monthly gross salary + monthly contributions + monthly fee
     * @type {number}
     * @memberof CostCalculatorCosts
     */
    'monthly_total': number;
}

