/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateRecurringIncentiveParamsAllOf
 */
export interface CreateRecurringIncentiveParamsAllOf {
    /**
     * How many times the payment will repeat. At the moment we only fully support monthly frequency.  This field is only necessary if the recurring incentive has an end date. 
     * @type {number}
     * @memberof CreateRecurringIncentiveParamsAllOf
     */
    'duration_in_months'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateRecurringIncentiveParamsAllOf
     */
    'employment_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRecurringIncentiveParamsAllOf
     */
    'type'?: CreateRecurringIncentiveParamsAllOfTypeEnum;
}

type CreateRecurringIncentiveParamsAllOfTypeEnum = 'acting_up_allowance' | 'allowance' | 'car_allowance' | 'health_and_wellness_allowance' | 'internet_allowance' | 'meal_allowance' | 'on_call_allowance' | 'parenthood_allowance' | 'phone_allowance' | 'relocation_allowance' | 'travel_allowance' | 'work_from_home_allowance' | 'bonus' | 'holiday_bonus' | 'referral_bonus' | 'retention_bonus' | 'commission' | 'other' | 'overtime' | 'stipend'


