/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DeleteRecurringIncentiveResponseData } from './delete-recurring-incentive-response-data';

/**
 * `\"status\": \"ok\"` indicates that any recurring incentives with `pending` status were successfully deleted.  `already_scheduled_incentives` returns a list of incentives that were already scheduled for payout and as such, cannot be deleted. You will notice that these incentives do not have a `pending` status. 
 * @export
 * @interface DeleteRecurringIncentiveResponse
 */
export interface DeleteRecurringIncentiveResponse {
    /**
     * 
     * @type {DeleteRecurringIncentiveResponseData}
     * @memberof DeleteRecurringIncentiveResponse
     */
    'data': DeleteRecurringIncentiveResponseData;
}

