/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyDefinition } from './currency-definition';
import { ExpenseReviewer } from './expense-reviewer';

/**
 * Expense
 * @export
 * @interface Expense
 */
export interface Expense {
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof Expense
     */
    'amount': number;
    /**
     * Categories allowed for an expense
     * @type {string}
     * @memberof Expense
     */
    'category'?: ExpenseCategoryEnum;
    /**
     * 
     * @type {number}
     * @memberof Expense
     */
    'converted_amount': number;
    /**
     * 
     * @type {CurrencyDefinition}
     * @memberof Expense
     */
    'converted_currency': CurrencyDefinition;
    /**
     * 
     * @type {number}
     * @memberof Expense
     */
    'converted_tax_amount': number;
    /**
     * 
     * @type {CurrencyDefinition}
     * @memberof Expense
     */
    'currency': CurrencyDefinition;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'employment_id': string;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'expense_date': string;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'invoice_period'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'notes'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'reason'?: string | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof Expense
     */
    'receipts'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    'reviewed_at'?: string | null;
    /**
     * 
     * @type {ExpenseReviewer}
     * @memberof Expense
     */
    'reviewer'?: ExpenseReviewer | null;
    /**
     * Expense status
     * @type {string}
     * @memberof Expense
     */
    'status'?: ExpenseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Expense
     */
    'tax_amount': number;
}

type ExpenseCategoryEnum = 'education_training' | 'home_office' | 'meals' | 'other' | 'phone_utilities' | 'tech_equipment' | 'travel' | 'coworking'
type ExpenseStatusEnum = 'canceled' | 'pending' | 'declined' | 'approved' | 'processing' | 'reimbursed'


