/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country } from './country';
import { PricingPlanDetails } from './pricing-plan-details';

/**
 * 
 * @export
 * @interface FullParams
 */
export interface FullParams {
    /**
     * Home address information. As its properties may vary depending on the country,                you must query the [Show form schema](https://gateway.remote.com/v1/docs/openapi.html) endpoint             passing the country code and `address_details` as path parameters.
     * @type {object}
     * @memberof FullParams
     */
    'address_details'?: object;
    /**
     * Administrative information. As its properties may vary depending on the country,                you must query the [Show form schema](https://gateway.remote.com/v1/docs/openapi.html) endpoint             passing the country code and `administrative_details` as path parameters.
     * @type {object}
     * @memberof FullParams
     */
    'administrative_details'?: object;
    /**
     * Bank account information. As its properties may vary depending on the country,                you must query the [Show form schema](https://gateway.remote.com/v1/docs/openapi.html) endpoint             passing the country code and `bank_account_details` as path parameters.
     * @type {object}
     * @memberof FullParams
     */
    'bank_account_details'?: object;
    /**
     * Employment basic information. As its properties may vary depending on the country,                you must query the [Show form schema](https://gateway.remote.com/v1/docs/openapi.html) endpoint             passing the country code and `employment_basic_information` as path parameters.
     * @type {object}
     * @memberof FullParams
     */
    'basic_information'?: object;
    /**
     * Billing address information. As its properties may vary depending on the country,                you must query the [Show form schema](https://gateway.remote.com/v1/docs/openapi.html) endpoint             passing the country code and `billing_address_details` as path parameters.
     * @type {object}
     * @memberof FullParams
     */
    'billing_address_details'?: object;
    /**
     * 
     * @type {string}
     * @memberof FullParams
     */
    'company_id'?: string;
    /**
     * Contract information. As its properties may vary depending on the country,                you must query the [Show form schema](https://gateway.remote.com/v1/docs/openapi.html) endpoint             passing the country code and `contract_details` as path parameters.
     * @type {object}
     * @memberof FullParams
     */
    'contract_details'?: object;
    /**
     * 
     * @type {Country}
     * @memberof FullParams
     */
    'country'?: Country;
    /**
     * The department of the employment. The department must belong to the same company as the employment. 
     * @type {string}
     * @memberof FullParams
     */
    'department_id'?: string;
    /**
     * Emergency contact information. As its properties may vary depending on the country,                you must query the [Show form schema](https://gateway.remote.com/v1/docs/openapi.html) endpoint             passing the country code and `emergency_contact_details` as path parameters.
     * @type {object}
     * @memberof FullParams
     */
    'emergency_contact_details'?: object;
    /**
     * 
     * @type {string}
     * @memberof FullParams
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof FullParams
     */
    'job_title'?: string;
    /**
     * The user id of the manager, who should have an `admin`, `owner` or `people_manager` role. You can find these users by querying the [Company Managers endpoint](https://gateway.remote.com/v1/docs/openapi.html). **Update of this field is only available for active employments.** 
     * @type {string}
     * @memberof FullParams
     */
    'manager_id'?: string;
    /**
     * Personal details information. As its properties may vary depending on the country,                you must query the [Show form schema](https://gateway.remote.com/v1/docs/openapi.html) endpoint             passing the country code and `personal_details` as path parameters.
     * @type {object}
     * @memberof FullParams
     */
    'personal_details'?: object;
    /**
     * 
     * @type {PricingPlanDetails}
     * @memberof FullParams
     */
    'pricing_plan_details'?: PricingPlanDetails;
}

