/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Remote advises not to inform the employee of their termination until we review your request for legal risks. When we approve your request, you can inform the employee and we’ll take it from there. This field is only required if employee was informed before creating the offboarding request.
 * @export
 * @interface TerminationDetailsParamsEmployeeAwareness
 */
export interface TerminationDetailsParamsEmployeeAwareness {
    /**
     * When the employee was told about the termination.
     * @type {string}
     * @memberof TerminationDetailsParamsEmployeeAwareness
     */
    'date'?: string | null;
    /**
     * Notes describing how the termination was shared with the employee. Remote advises being as specific as possible, and include details about the employee’s response, if applicable.
     * @type {string}
     * @memberof TerminationDetailsParamsEmployeeAwareness
     */
    'note'?: string | null;
}

