/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OffboardingFile } from './offboarding-file';
import { TerminationDetailsParamsEmployeeAwareness } from './termination-details-params-employee-awareness';

/**
 * 
 * @export
 * @interface TerminationDetailsParams
 */
export interface TerminationDetailsParams {
    /**
     * Additional details regarding the termination process.
     * @type {string}
     * @memberof TerminationDetailsParams
     */
    'additional_comments'?: string;
    /**
     * Confidential requests are visible for who authorized the token or integration. Non-confidential requests are visible to all admins in the company.
     * @type {boolean}
     * @memberof TerminationDetailsParams
     */
    'confidential': boolean;
    /**
     * 
     * @type {TerminationDetailsParamsEmployeeAwareness}
     * @memberof TerminationDetailsParams
     */
    'employee_awareness'?: TerminationDetailsParamsEmployeeAwareness;
    /**
     * Remote will use this email address for post-termination communication. If it is not provided, this field will be derived from the employment record. Therefore, it is important to ensure that it is not a company email. 
     * @type {string}
     * @memberof TerminationDetailsParams
     */
    'personal_email'?: string;
    /**
     * In most cases, employee needs to be notified before termination. The required notice period depends on local labor laws, the employment agreement, and other factors. Remote will use those factors to determine the required notice period. Please note that we cannot commit to a termination date until we conduct a full review of the information you submit.
     * @type {string}
     * @memberof TerminationDetailsParams
     */
    'proposed_termination_date': string;
    /**
     * Description of the reason for termination
     * @type {string}
     * @memberof TerminationDetailsParams
     */
    'reason_description': string;
    /**
     * Possible reasons for offboarding risk assessment
     * @type {Array<string>}
     * @memberof TerminationDetailsParams
     */
    'risk_assessment_reasons': Array<TerminationDetailsParamsRiskAssessmentReasonsEnum>;
    /**
     * Choose an accurate termination reason to avoid unfair or unlawful dismissal claims.  If the termination is created before the employee\'s start date, this field will be set to `cancellation_before_start_date`. 
     * @type {string}
     * @memberof TerminationDetailsParams
     */
    'termination_reason': TerminationDetailsParamsTerminationReasonEnum;
    /**
     * Any supporting documents regarding the termination reason
     * @type {Array<OffboardingFile>}
     * @memberof TerminationDetailsParams
     */
    'termination_reason_files'?: Array<OffboardingFile>;
    /**
     * Paid time off accuracy  Typically, any vacation pay accrued and unpaid at the time of termination must be paid out to the employee. To avoid overpaying or underpaying, please make sure we have an accurate account of their paid time off by querying the [Show Time Off Balance](https://gateway.remote.com/v1/docs/openapi.html) endpoint, filtering by the `employment_id`. This optional document should be sent in case of any discrepancies. 
     * @type {OffboardingFile}
     * @memberof TerminationDetailsParams
     */
    'timesheet_file'?: OffboardingFile;
    /**
     * Whether is it likely or not that the employee will challenge their termination
     * @type {boolean}
     * @memberof TerminationDetailsParams
     */
    'will_challenge_termination': boolean;
    /**
     * If it is likely that the employee will challenge their termination, please provide additional details explaining the risk
     * @type {string}
     * @memberof TerminationDetailsParams
     */
    'will_challenge_termination_description'?: string;
}

type TerminationDetailsParamsRiskAssessmentReasonsEnum = 'caring_responsibilities' | 'disabled_or_health_condition' | 'family_leave' | 'member_of_union_or_works_council' | 'none_of_these' | 'pregnant_or_breastfeeding' | 'reported_concerns_with_workplace' | 'requested_medical_or_family_leave' | 'sick_leave'
type TerminationDetailsParamsTerminationReasonEnum = 'cancellation_before_start_date' | 'compliance_issue' | 'conversion_to_contractor' | 'dissatisfaction_with_remote_service' | 'end_of_fixed_term_contract_compliance_issue' | 'end_of_fixed_term_contract_incapacity_to_perform_inherent_duties' | 'end_of_fixed_term_contract_local_regulations_max_term_reached' | 'end_of_fixed_term_contract_misconduct' | 'end_of_fixed_term_contract_operational_reasons' | 'end_of_fixed_term_contract_other' | 'end_of_fixed_term_contract_performance' | 'end_of_fixed_term_contract_redundancy' | 'end_of_fixed_term_contract_values' | 'gross_misconduct' | 'incapacity_to_perform_inherent_duties' | 'job_abandonment' | 'mutual_agreement' | 'other' | 'performance' | 'values' | 'workforce_reduction'


