/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TerminationOffboardingEmployeeAwareness } from './termination-offboarding-employee-awareness';

/**
 * 
 * @export
 * @interface TerminationOffboarding
 */
export interface TerminationOffboarding {
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'additional_comments': string;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'agrees_to_pto_amount'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TerminationOffboarding
     */
    'confidential': boolean;
    /**
     * 
     * @type {TerminationOffboardingEmployeeAwareness}
     * @memberof TerminationOffboarding
     */
    'employee_awareness'?: TerminationOffboardingEmployeeAwareness;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'employment_id': string;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'proposed_termination_date': string;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'reason_description': string;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'requested_by': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TerminationOffboarding
     */
    'risk_assessment_reasons': Array<TerminationOffboardingRiskAssessmentReasonsEnum>;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'status': TerminationOffboardingStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'submitted_at': string;
    /**
     * Most updated termination date for the offboarding. This date is subject to change through the offboarding process even after it is finalized.
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'termination_date': string | null;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'termination_reason': TerminationOffboardingTerminationReasonEnum;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'type': TerminationOffboardingTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TerminationOffboarding
     */
    'will_challenge_termination': boolean;
    /**
     * 
     * @type {string}
     * @memberof TerminationOffboarding
     */
    'will_challenge_termination_description'?: string;
}

type TerminationOffboardingRiskAssessmentReasonsEnum = 'caring_responsibilities' | 'disabled_or_health_condition' | 'family_leave' | 'member_of_union_or_works_council' | 'none_of_these' | 'pregnant_or_breastfeeding' | 'reported_concerns_with_workplace' | 'requested_medical_or_family_leave' | 'sick_leave'
type TerminationOffboardingStatusEnum = 'submitted' | 'in_review' | 'done' | 'canceled'
type TerminationOffboardingTerminationReasonEnum = 'cancellation_before_start_date' | 'compliance_issue' | 'conversion_to_contractor' | 'dissatisfaction_with_remote_service' | 'end_of_fixed_term_contract_compliance_issue' | 'end_of_fixed_term_contract_incapacity_to_perform_inherent_duties' | 'end_of_fixed_term_contract_local_regulations_max_term_reached' | 'end_of_fixed_term_contract_misconduct' | 'end_of_fixed_term_contract_operational_reasons' | 'end_of_fixed_term_contract_other' | 'end_of_fixed_term_contract_performance' | 'end_of_fixed_term_contract_redundancy' | 'end_of_fixed_term_contract_values' | 'gross_misconduct' | 'incapacity_to_perform_inherent_duties' | 'job_abandonment' | 'mutual_agreement' | 'other' | 'performance' | 'values' | 'workforce_reduction'
type TerminationOffboardingTypeEnum = 'termination'


