/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeoffDay } from './timeoff-day';
import { TimeoffType } from './timeoff-type';

/**
 * 
 * @export
 * @interface Timeoff
 */
export interface Timeoff {
    /**
     * 
     * @type {string}
     * @memberof Timeoff
     */
    'approved_at'?: string | null;
    /**
     * The field matches the `id` of a user in the Remote Platform that has permission to approve time off requests. [Available users][] can be found fetching the [List Company Manager][] endpoint.  [Available users]: https://support.remote.com/hc/en-us/articles/360054668651-Approving-Declining-time-off-requests#h_01G0014GZKZ3EMN6P7C99HAK55 [List Company Manager]: https://gateway.remote.com/v1/docs/openapi.html#tag/Company-Managers 
     * @type {string}
     * @memberof Timeoff
     */
    'approver_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Timeoff
     */
    'cancel_reason'?: string | null;
    /**
     * Optional UTC date time in YYYY-MM-DDTHH:mm:ss format
     * @type {string}
     * @memberof Timeoff
     */
    'cancelled_at'?: string | null;
    /**
     * 
     * @type {any}
     * @memberof Timeoff
     */
    'document'?: any;
    /**
     * 
     * @type {string}
     * @memberof Timeoff
     */
    'employment_id': string;
    /**
     * 
     * @type {string}
     * @memberof Timeoff
     */
    'end_date': string;
    /**
     * 
     * @type {string}
     * @memberof Timeoff
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Timeoff
     */
    'notes'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Timeoff
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof Timeoff
     */
    'status': string;
    /**
     * 
     * @type {Array<TimeoffDay>}
     * @memberof Timeoff
     */
    'timeoff_days': Array<TimeoffDay>;
    /**
     * 
     * @type {TimeoffType}
     * @memberof Timeoff
     */
    'timeoff_type': TimeoffType;
    /**
     * [TZ identifier](https://www.iana.org/time-zones)
     * @type {string}
     * @memberof Timeoff
     */
    'timezone': string;
}

