/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateCompanyParams
 */
export interface UpdateCompanyParams {
    /**
     * Fields can vary depending on the country. Please, check the required fields structure using the [Show form schema endpoint](https://gateway.remote.com/v1/docs/openapi.html). Use the desired country and `address_details` as the form name for the placeholders. The response complies with the [JSON Schema](https://remote.com/resources/api/how-json-schemas-work) specification. 
     * @type {object}
     * @memberof UpdateCompanyParams
     */
    'address_details'?: object;
    /**
     * Fields can vary depending on the country. Please, check the required fields structure using the [Show form schema endpoint](https://gateway.remote.com/v1/docs/openapi.html). Use the desired country and `bank_account_details` as the form name for the placeholders. The response complies with the [JSON Schema](https://remote.com/resources/api/how-json-schemas-work) specification. 
     * @type {object}
     * @memberof UpdateCompanyParams
     */
    'bank_account_details'?: object;
    /**
     * Country of company address
     * @type {string}
     * @memberof UpdateCompanyParams
     */
    'country_code'?: string;
    /**
     * Desired currency for invoicing and displaying converted salaries in Remote UI regardless of the employee\'s country.  This field is only accepted if company is in status `pending`. Please contact Remote if you wish to update it. 
     * @type {string}
     * @memberof UpdateCompanyParams
     */
    'desired_currency'?: UpdateCompanyParamsDesiredCurrencyEnum;
    /**
     * This field is only accepted if company is in status `pending`. Please contact Remote if you wish to update it. 
     * @type {string}
     * @memberof UpdateCompanyParams
     */
    'name'?: string;
    /**
     * A phone number the company can be contacted with.
     * @type {string}
     * @memberof UpdateCompanyParams
     */
    'phone_number'?: string;
    /**
     * The company registration number. This field or tax_number (but not both) should be submitted.  This field is only accepted if company is in status `pending`. 
     * @type {string}
     * @memberof UpdateCompanyParams
     */
    'registration_number'?: string;
    /**
     *   The tax identifier of the company. This field or registration_number (but not both) should be submitted.    This field is only accepted if company is in status `pending`. 
     * @type {string}
     * @memberof UpdateCompanyParams
     */
    'tax_number'?: string;
}

type UpdateCompanyParamsDesiredCurrencyEnum = 'AUD' | 'CAD' | 'CHF' | 'DKK' | 'EUR' | 'GBP' | 'JPY' | 'NOK' | 'NZD' | 'SEK' | 'SGD' | 'USD'


