/*
Remote API

Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom. 

Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more. 

Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhookCallback
 */
export interface WebhookCallback {
    /**
     * 
     * @type {string}
     * @memberof WebhookCallback
     */
    'id': string;
    /**
     * This key will be used to sign the signature provided with webhook requests we send to the `url` you provided for this webhook callback.  The webhook signature will be included in a custom header, `X-Remote-Signature`. You can use this signature to verify that requests are coming from Remote and not some unauthorized third-party. 
     * @type {string}
     * @memberof WebhookCallback
     */
    'signing_key'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookCallback
     */
    'subscribed_events'?: Array<WebhookCallbackSubscribedEventsEnum>;
    /**
     * 
     * @type {string}
     * @memberof WebhookCallback
     */
    'url': string;
}

type WebhookCallbackSubscribedEventsEnum = 'billing_document.issued' | 'contract_amendment.canceled' | 'contract_amendment.deleted' | 'contract_amendment.done' | 'contract_amendment.review_started' | 'contract_amendment.submitted' | 'employment_contract.active_contract_updated' | 'employment.account.updated' | 'employment.details.updated' | 'employment.onboarding_task.completed' | 'employment.onboarding.completed' | 'employment.personal_information.updated' | 'employment.user_status.activated' | 'employment.user_status.deactivated' | 'expense.approved' | 'expense.declined' | 'expense.deleted' | 'expense.reimbursed' | 'expense.submitted' | 'expense.updated' | 'incentive.created' | 'incentive.deleted' | 'incentive.paid' | 'incentive.processing_started' | 'incentive.updated' | 'offboarding.deleted' | 'offboarding.done' | 'offboarding.review_started' | 'offboarding.submitted' | 'payslip.released' | 'timeoff.approved' | 'timeoff.canceled' | 'timeoff.date_changed' | 'timeoff.declined' | 'timeoff.requested' | 'timeoff.taken' | 'timeoff.updated'


